### PR TITLE
Option in Armor Status mod: Make ArmorHud not render anything if there is no armor on

### LINKED ISSUE #11: armor hud background still shows when no armor is equipped
e

not really a big bug

### PR DESCRIPTION
**Pull request by jordoncodes**
fixes #11

### CODE REVIEW

**Comment by TheKodeToad** [comment]
This allocates a new array every frame.

**Comment by jordoncodes** [comment]
> This allocates a new array every frame.

it no longer does that

**Comment by duplidev** [comment]
I wouldn't count this as a bug. I think it comes down to preference. So perhaps, there could be an option for this instead.

**Comment by jordoncodes** [comment]
okay

**Comment by jordoncodes** [comment]
done

**Pull request merged**
